/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package labAssignment2;


/**
 *
 * @author midhu
 */
import javax.swing.JOptionPane;
public class JavaLab2 extends javax.swing.JFrame {

    /**
     * Creates new form JavaLab2
     */
    public JavaLab2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        genderJbuttongroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        firstnameJlabel = new javax.swing.JLabel();
        lastnameJlabel = new javax.swing.JLabel();
        firstnameJtext = new javax.swing.JTextField();
        lastnameJtext = new javax.swing.JTextField();
        genderJlabel = new javax.swing.JLabel();
        maleJradio = new javax.swing.JRadioButton();
        femaleJradio = new javax.swing.JRadioButton();
        ageJlabel = new javax.swing.JLabel();
        submitJbutton = new javax.swing.JButton();
        ageJtextfield = new javax.swing.JTextField();
        emailJtextfield = new javax.swing.JTextField();
        emailJlabel = new javax.swing.JLabel();
        numberJlabel = new javax.swing.JLabel();
        numberJtextfield = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        firstnameJlabel.setText("First name :");

        lastnameJlabel.setText("Last name : ");

        firstnameJtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameJtextActionPerformed(evt);
            }
        });

        lastnameJtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameJtextActionPerformed(evt);
            }
        });

        genderJlabel.setText("Gender :");

        genderJbuttongroup.add(maleJradio);
        maleJradio.setText("Male");
        maleJradio.setActionCommand("MALE");
        maleJradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleJradioActionPerformed(evt);
            }
        });

        genderJbuttongroup.add(femaleJradio);
        femaleJradio.setText("Female");
        femaleJradio.setActionCommand("FEMALE");

        ageJlabel.setText("Age :");

        submitJbutton.setText("Submit");
        submitJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJbuttonActionPerformed(evt);
            }
        });

        ageJtextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageJtextfieldActionPerformed(evt);
            }
        });

        emailJtextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailJtextfieldActionPerformed(evt);
            }
        });

        emailJlabel.setText("Email:");

        numberJlabel.setText("Phone number:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(submitJbutton)
                .addGap(160, 160, 160))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(numberJlabel)
                    .addComponent(ageJlabel)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(firstnameJlabel)
                                .addComponent(lastnameJlabel)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(genderJlabel)))
                    .addComponent(emailJlabel))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(femaleJradio)
                        .addComponent(maleJradio)
                        .addComponent(firstnameJtext, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                        .addComponent(lastnameJtext))
                    .addComponent(emailJtextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(numberJtextfield)
                    .addComponent(ageJtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnameJlabel)
                    .addComponent(firstnameJtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnameJtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastnameJlabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderJlabel)
                    .addComponent(maleJradio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(femaleJradio)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageJlabel)
                    .addComponent(ageJtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailJtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailJlabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberJlabel)
                    .addComponent(numberJtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(submitJbutton)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstnameJtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameJtextActionPerformed
        // TODO add your handling code here:
        System.out.println(this.firstnameJtext.getText());
    }//GEN-LAST:event_firstnameJtextActionPerformed

    private void lastnameJtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameJtextActionPerformed
        // TODO add your handling code here:
        System.out.print(this.lastnameJtext.getText());
    }//GEN-LAST:event_lastnameJtextActionPerformed

    private void maleJradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleJradioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleJradioActionPerformed

    private void submitJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJbuttonActionPerformed
        // TODO add your handling code here:
        try{
             String fname = this.firstnameJtext.getText() ;
        String lname = this.lastnameJtext.getText() ;
        String gender = this.genderJbuttongroup.getSelection().getActionCommand() ;
        String email = this.emailJtextfield.getText() ;
        String age = this.ageJtextfield.getText() ;
        String number = this.numberJtextfield.getText() ;
        String displayMessage = "Name : " + fname+ lname+ " \n Gender : "+ gender+ "\n Age : " + age+ "\n Email id : " + email+ "\n Number : " + number;
        System.out.println(this.firstnameJtext.getText());
        System.out.println(this.lastnameJtext.getText());
        System.out.println(this.genderJbuttongroup.getSelection().getActionCommand());
        System.out.println(this.emailJtextfield.getText());
        System.out.println(this.ageJtextfield.getText());
        System.out.println(this.numberJtextfield.getText());
        JOptionPane.showMessageDialog(this,displayMessage);
        }
        catch(Exception e){
            String errorMessage = "You must enter values in all fields";
            JOptionPane.showMessageDialog(this,errorMessage);
        }
        String fname = this.firstnameJtext.getText() ;
        String lname = this.lastnameJtext.getText() ;
        String gender = this.genderJbuttongroup.getSelection().getActionCommand() ;
        String email = this.emailJtextfield.getText() ;
        String age = this.ageJtextfield.getText() ;
        String number = this.numberJtextfield.getText() ;
        String displayMessage = "Name : " + fname+ lname+ " \n Gender : "+ gender+ "\n Age : " + age+ "\n Email id : " + email+ "\n Number : " + number;
        System.out.println(this.firstnameJtext.getText());
        System.out.println(this.lastnameJtext.getText());
        System.out.println(this.genderJbuttongroup.getSelection().getActionCommand());
        System.out.println(this.emailJtextfield.getText());
        System.out.println(this.ageJtextfield.getText());
        System.out.println(this.numberJtextfield.getText());
        JOptionPane.showMessageDialog(this,displayMessage);
    }//GEN-LAST:event_submitJbuttonActionPerformed

    private void ageJtextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageJtextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageJtextfieldActionPerformed

    private void emailJtextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailJtextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailJtextfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaLab2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaLab2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaLab2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaLab2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaLab2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageJlabel;
    private javax.swing.JTextField ageJtextfield;
    private javax.swing.JLabel emailJlabel;
    private javax.swing.JTextField emailJtextfield;
    private javax.swing.JRadioButton femaleJradio;
    private javax.swing.JLabel firstnameJlabel;
    private javax.swing.JTextField firstnameJtext;
    private javax.swing.ButtonGroup genderJbuttongroup;
    private javax.swing.JLabel genderJlabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lastnameJlabel;
    private javax.swing.JTextField lastnameJtext;
    private javax.swing.JRadioButton maleJradio;
    private javax.swing.JLabel numberJlabel;
    private javax.swing.JTextField numberJtextfield;
    private javax.swing.JButton submitJbutton;
    // End of variables declaration//GEN-END:variables
}
